name: Release

on:
    push:
        branches: ['main']
env:
    TURBO_TELEMETRY_DISABLED: 1

jobs:
    release:
        name: Build and publish
        if: ${{ github.repository_owner == 'jobindex-open' }}
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: write # To create releases
            id-token: write # For trusted publishing
            pull-requests: write # To create pull requests
        steps:
            - name: Checkout source
              uses: actions/checkout@v6
              with:
                  fetch-depth: 2

            - name: Pre-install yarn
              run: npm install -g yarn

            - name: Install turbo
              run: npm install -g turbo

            - name: Use Node.js 22.x
              uses: actions/setup-node@v6
              with:
                  node-version: 22.x
                  cache: 'yarn'

            - name: Install
              run: yarn install --frozen-lockfile

            # - name: Cache Turbo
            #   uses: actions/cache@v5
            #   with:
            #       path: .turbo
            #       key: ${{ runner.os }}-turbo-${{ hashFiles('**/*.ts') }}
            #       restore-keys: |
            #           ${{ runner.os }}-turbo-
            - name: Build production bundle
              run: yarn build
              # run: turbo run build build:types --cache-dir=".turbo"

            - name: Install latest version of npm
              run: npm install -g npm@latest

            - name: Publish to npm
              id: changesets
              uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
              with:
                  publish: npx @changesets/cli publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: '' # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
                  # NODE_AUTH_TOKEN: ''
